export const PROCESS_START = "PROCESS_START";
export const PROCESS_END = "PROCESS_END";

// USER CONSTANT
export const PROCESS_LOGIN_START = "PROCESS_LOGIN_START";
export const PROCESS_REGISTER_START = "PROCESS_REGISTER_START";
export const PROCESS_LOGOUT_START = "PROCESS_LOGOUT_START";
export const PROCESS_GET_ALL_START = "PROCESS_GET_ALL_START";

export const PROCESS_ERROR = "PROCESS_ERROR";
export const UNAUTHORIZED = "UNAUTHORIZED";
