// User Action Type List

const UserActionTypes = {
  LOGIN_DATA: "LOGIN_DATA",
  REGISTER_DATA: "REGISTER_DATA",
  FLUSH_LOGIN_DATA: "FLUSH_LOGIN_DATA",
  FLUSH_REGISTER_DATA: "FLUSH_REGISTER_DATA",
  GET_ALL_DATA: "GET_ALL_DATA",
  GET_ONE_DATA: "GET_ONE_DATA",
  PROCESS_LOGIN_START: "PROCESS_LOGIN_START",
  PROCESS_REGISTER_START: "PROCESS_REGISTER_START",
  PROCESS_LOGOUT_START: "PROCESS_LOGOUT_START",
  PROCESS_GET_ALL_START: "PROCESS_GET_ALL_START",
  PROCESS_GET_ONE_START: "PROCESS_GET_ONE_START",
  ERROR_LOGIN: "ERROR_LOGIN",
  ERROR_REGISTER: "ERROR_REGISTER",
  ERROR_LOGOUT: "ERROR_LOGOUT",
  ERROR_GET_ALL: "ERROR_GET_ALL",
  ERROR_GET_ONE: "ERROR_GET_ONE",
};

export default UserActionTypes;
